from django.urls import path,include
from .import views
urlpatterns = [
    path('',views.home,name='home'),
    path('login/',views.login,name='login'),
    path('signup/',views.signup,name='signup'),
    path('main_login',views.main_login,name='main_login'),
    path('admin_page',views.admin_page,name='admin_page'),
    path('add_category/',views.add_category,name='add_category'),
    path('register_category',views.register_category,name='register_category'),
    path('add_product',views.add_product,name='add_product'),
    path('register_product',views.register_product,name='register_product'),
    path('view_product',views.view_product,name='view_product'),
    path('product_delete/<int:pk>',views.product_delete,name='product_delete'),
    path('admin_logout',views.admin_logout,name='admin_logout'),
    path('register_customer',views.register_customer,name='register_customer'),
    path('view_users',views.view_users,name='view_users'),
    path('customer_delete/<int:pk>',views.customer_delete,name='customer_delete'),
    path('navbarcustomer',views.navbarcustomer,name='navbarcustomer'),
    path('customer_products/<int:pk>',views.customer_products,name='customer_products'),
    path('add_to_cart/<int:pk>',views.add_to_cart,name='add_to_cart'),
    path('cart_remove/<int:pk>',views.cart_remove,name='cart_remove'),
    path('cart_view',views.cart_view,name='cart_view'),
    path('customer_logout',views.customer_logout,name='customer_logout'),
    path('review',views.review,name='review'),
    path('aboutus',views.aboutus,name='aboutus'),
    path('navbarhome',views.navbarhome,name='navbarhome'),
    path('footer_customer',views.footer_customer,name='footer_customer'),
    path('all_products',views.all_products,name='all_products'),
    path('increment/<int:pk>',views.increment,name='increment'),
    path('decrement/<int:pk>',views.decrement,name='decrement'),
    path('checkout',views.checkout,name='checkout'),
    path('checkout_process',views.checkout_process,name='checkout_process'),
]
